=== jcicerof/java21pro/chapter21/coalData.dtd
<!ELEMENT coalData (record?)+ >
<!ELEMENT record (fips?, country?, year?, anthraciteProduction?)* >
<!ELEMENT fips (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT anthraciteProduction (#PCDATA)>

=== jcicerof/java21pro/chapter21/CoalTotals.xml
<?xml version="1.0"?>
<!DOCTYPE Library SYSTEM "coalData.dtd">
<coalData>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1990</year>
      <anthraciteProduction>0.0</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1991</year>
      <anthraciteProduction>0.0</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1992</year>
      <anthraciteProduction>0.0</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1993</year>
      <anthraciteProduction>174.165194805424</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1994</year>
      <anthraciteProduction>242.50849909616</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1995</year>
      <anthraciteProduction>304.237935229728</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1996</year>
      <anthraciteProduction>308.64718066784</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1997</year>
      <anthraciteProduction>319.67029426312</anthraciteProduction>
  </record>
  <record>
    <fips>PL</fips>
      <country>Poland</country>
      <year>1998</year>
      <anthraciteProduction>319.67029426312</anthraciteProduction>
  </record>
</coalData>
